kind: pipeline
name: kube-cleanup-operator-arm

workspace:
  base: /go

steps:
- name: clone-kube-cleanup-operator
  image: drone/git
  commands: 
  - git clone https://github.com/lwolf/kube-cleanup-operator src/github.com/lwolf/kube-cleanup-operator

- name: build-kube-cleanup-operator
  image: golang:buster
  commands:
  - cd src/github.com/lwolf/kube-cleanup-operator
  - go get -u github.com/golang/dep/cmd/dep
  - make install_deps
  - make build
  - cp bin/kube-cleanup-operator /go
  - cp Dockerfile /go
  - sed -i '' 's=FROM alpine=FROM arm32v7/alpine=g' /go/Dockerfile

- name: publish-kube-cleanup-operator
  image: docker-registry:5000/drone-plugins/kaniko:latest
  settings:
    registry: docker.artificialcreature.com
    repo: lwolf/kube-cleanup-operator
    tags: latest
    log: info