kind: pipeline
name: kube-cleanup-operator-arm

# platform:
#   os: linux
#   architecture: arm
#   variant: 7

workspace:
  base: /go
  path: src/github.com/lwolf/kube-cleanup-operator

steps:
- name: clone-kube-cleanup-operator
  image: drone/git
  commands: 
  - git clone https://github.com/lwolf/kube-cleanup-operator src/github.com/lwolf/kube-cleanup-operator

- name: build-kube-cleanup-operator
  image: golang:buster
  commands:
  #- apt update
  #- apt install -y --no-install-recommends make
  - cd src/github.com/lwolf/kube-cleanup-operator
  - pwd
  - set
  - go get -u github.com/golang/dep/cmd/dep
  - make install_deps
  - make build
  - cp bin/kube-cleanup-operator /go

- name: publish-authelia
  image: docker-registry:5000/drone-plugins/kaniko:latest
  settings:
    registry: docker.artificialcreature.com
    repo: lwolf/kube-cleanup-operator
    tags: latest
    log: debug
    d