kind: pipeline
name: kube-cleanup-operator-arm

workspace:
  base: /go

steps:
# - name: clone-kube-cleanup-operator
#   image: drone/git
#   commands:
#   - git clone https://github.com/lwolf/kube-cleanup-operator src/github.com/lwolf/kube-cleanup-operator

- name: build-kube-cleanup-operator
  image: golang:alpine
  commands:
  - apk update
  - apk add --no-cache git make
  - go get -u -v github.com/lwolf/kube-cleanup-operator
  - go get -u -v github.com/golang/dep/cmd/dep
  - cd src/github.com/lwolf/kube-cleanup-operator
  - ls /go
  - sed -i 's;GOARCH=amd64;GOARM=7 GOARCH=arm;g' Makefile
  - make install_deps
  - ls -la
  - make build
  - ls -la
  - ls -la bin/ 
  - cp bin/kube-cleanup-operator /go
  - cp Dockerfile /go
  - sed -i 's;FROM alpine;FROM arm32v7/alpine;g' /go/Dockerfile

- name: publish-kube-cleanup-operator
  image: docker-registry:5000/drone-plugins/kaniko:latest
  settings:
    registry: docker.artificialcreature.com
    repo: lwolf/kube-cleanup-operator
    tags: latest
    log: info